CREATE OR REPLACE FUNCTION create_client(text) RETURNS boolean
AS 'MODULE_PATHNAME', 'create_client'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION destroy_client() RETURNS boolean
AS 'MODULE_PATHNAME', 'destroy_client'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION put_int8(text, text, int8) RETURNS int8
AS 'MODULE_PATHNAME', 'put_int8'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION get_int8(text, text) RETURNS int8
AS 'MODULE_PATHNAME', 'get_int8'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION put_text(text, text, text) RETURNS text
AS 'MODULE_PATHNAME', 'put_text'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION get_text(text, text) RETURNS text
AS 'MODULE_PATHNAME', 'get_text'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION delete_key(text, text) RETURNS boolean
AS 'MODULE_PATHNAME', 'delete_key'
LANGUAGE C STRICT;
