CREATE OR REPLACE FUNCTION create_client(text) RETURNS void
PARALLEL UNSAFE
AS 'MODULE_PATHNAME', 'create_client'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION destroy_client() RETURNS void
PARALLEL UNSAFE
AS 'MODULE_PATHNAME', 'destroy_client'
LANGUAGE C STRICT;
