CREATE OR REPLACE FUNCTION create_client(text) RETURNS void
AS 'MODULE_PATHNAME', 'create_client'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION destroy_client() RETURNS void
AS 'MODULE_PATHNAME', 'destroy_client'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION put_int8(text, text, int8) RETURNS void
AS 'MODULE_PATHNAME', 'put_int8'
LANGUAGE C STRICT;

-- CREATE OR REPLACE FUNCTION get_int8(text, text) RETURNS int8
-- AS 'MODULE_PATHNAME', 'get_int8'
-- LANGUAGE C STRICT;
